backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"
locale: "zh-Hant"
collections:
  - name: "blog"
    label: "文章"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - { label: "標題", name: "title", widget: "string" }
      #- { label: "Canonical", name: "canonical", widget: "string" }
      - { label: "摘要", name: "description", widget: "string" }
      - { label: "搜尋關鍵字詞", name: "keywords", widget: "string" }
      - { label: "作者", name: "author", widget: "string" }
      - { label: "發布日期", name: "date", widget: "datetime" }
      #- { label: "Tags", name: "tags", widget: "list", default: ["post"] } # post, featured
      - widget: "select"
        label: "標籤"
        name: "tags"
        multiple: true
        options: ["post", "featured"]
        default: ["post"]
      - { label: "上傳圖片", name: "image", widget: "image" }
      - { label: "圖片標題", name: "imageAlt", widget: "string" }
      - { label: "內容", name: "body", widget: "markdown" }
      #- { label: "Upload Leaflet", name: "leaflet", widget: "string" }
  - name: "class"
    label: "課程/興趣班"
    folder: "src/class"
    create: true
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "Canonical", name: "canonical", widget: "string" }
      - { label: "摘要", name: "description", widget: "string" }
      - { label: "搜尋關鍵字詞", name: "keywords", widget: "string" }
      - { label: "作者", name: "author", widget: "string" }
      - { label: "發布日期", name: "date", widget: "datetime" }
      #- { label: "Tags", name: "tags", widget: "list", default: ["class"] } # ace, class, chinese, english, math, tsa, kindergarten, other, sen, popular
      - widget: "select"
        label: "標籤"
        name: "tags"
        multiple: true
        options: ["class", "popular", "ace", "chinese", "english", "math", "tsa", "kindergarten", "other", "sen"]
        default: ["class"]
      - { label: "上傳圖片", name: "image", widget: "image" }
      - { label: "圖片標題", name: "imageAlt", widget: "string" }
      - { label: "內容", name: "body", widget: "markdown" }
      - { label: "上傳單張", name: "leaflet", widget: "string" }
  - name: "卡紙"
    label: "Card"
    folder: "src/card"
    create: true
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields:
      - { label: "標題", name: "title", widget: "string" }
      #- { label: "Canonical", name: "canonical", widget: "string" }
      - { label: "摘要", name: "description", widget: "string" }
      #- { label: "Search Keywords", name: "keywords", widget: "string" }
      - { label: "作者", name: "author", widget: "string" }
      - { label: "發表日期", name: "date", widget: "datetime" }
      #- { label: "Tags", name: "tags", widget: "list", default: ["card"] } # card
      - widget: "select"
        label: "標籤"
        name: "tags"
        multiple: true
        options: ["card", "star"]
        default: ["card"]
      - { label: "上傳圖片", name: "image", widget: "image" }
      - { label: "圖片標題", name: "imageAlt", widget: "string" }
      - { label: "內容", name: "body", widget: "markdown" }
      #- { label: "Upload Leaflet", name: "leaflet", widget: "string" }